name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/cicd
      - feature/check1
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: environment/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environment/dev

      - name: TFLint
        run: tflint
        working-directory: environment/dev

      - name: Checkov Security Scan
        run: checkov -d environment/dev

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: environment/dev